/**
 * dsh-read-aloud client 构建：把 src/client/index.ts 的 __mirror body 抽取为
 * lib/client.js（window.__ModuleLoader__.load 包裹的浏览器 bundle，参照
 * dsh-novel-workbench 同款手搓方案——零第三方构建依赖，无需 tsdown）。
 *
 * bundle 工厂闭包提供：React（ModuleLoader require）、host（fetch RPC 桥）、
 * API_BASE。body 本身保持纯 JS（见 src/client/index.ts 头部约定）。
 *
 * 产物断言（与注入器预检对齐）：
 *  - 含 __ModuleLoader__ 特征（buildFreshnessProblems 的 tsdown 特征判据）
 *  - 含 inject: ['slots'...] 与 register({ name: 'conversation.input.left'... })
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')
const PKG_ID = '@dsh-external/dsh-read-aloud'
const API_PREFIX = '/' + PKG_ID + '/api'
const SRC = join(ROOT, 'src', 'client', 'index.ts')
const OUT = join(ROOT, 'lib', 'client.js')

const src = readFileSync(SRC, 'utf8')

// 抽取 __mirror 内 body（`return { ... }` 的插件对象字面量）
const m = /const __mirror = \(function \(\) \{([\s\S]*)\}\)\(\)[\s]*export default __mirror[\s]*$/.exec(src)
if (!m) throw new Error('build-client: 找不到 __mirror 抽取锚点（检查 src/client/index.ts 尾部结构）')
const body = m[1].trim()
if (!/name:\s*['"]@dsh-external\/dsh-read-aloud['"]/.test(body)) throw new Error('build-client: body 缺 name 锚点')
if (!/inject:\s*\[[^\]]*['"]slots['"]/.test(body)) throw new Error('build-client: body 缺 inject 含 slots 锚点')
if (!/slots\.register\(\{\s*name:\s*'conversation\.input\.left'/.test(body)) throw new Error('build-client: body 缺 conversation.input.left register 锚点')

const bundle = [
  '/* GENERATED by scripts/build-client.mjs — 勿手改 lib/client.js，改源后重新构建 */',
  'window.__ModuleLoader__.load({',
  '  id: ' + JSON.stringify(PKG_ID) + ',',
  '  factory: (require) => {',
  '    var module = { exports: {} };',
  '    var exports = module.exports;',
  '    Object.defineProperty(exports, Symbol.toStringTag, { value: "Module" });',
  '    const React = require("react");',
  '    const API_BASE = ' + JSON.stringify(API_PREFIX) + ';',
  '    async function fetchJson(name, args) {',
  '      const res = await fetch(API_BASE + "/" + encodeURIComponent(name), {',
  '        method: "POST",',
  '        headers: { "content-type": "application/json" },',
  '        body: JSON.stringify(args === undefined ? {} : args),',
  '      });',
  '      let data = null;',
  '      try { data = await res.json(); } catch (e) { throw new Error("read-aloud RPC 非 JSON 响应: HTTP " + res.status); }',
  '      if (!data || data.ok !== true) throw new Error((data && data.error) || ("read-aloud RPC 失败: " + name));',
  '      return data.result;',
  '    }',
  '    const host = { call: fetchJson };',
  '    const __plugin = (function () {',
  body,
  '    })();',
  '    exports.name = __plugin.name;',
  '    exports.inject = __plugin.inject;',
  '    exports.apply = __plugin.apply;',
  '    return module.exports;',
  '  }',
  '});',
  '',
].join('\n')

mkdirSync(dirname(OUT), { recursive: true })
writeFileSync(OUT, bundle, 'utf8')
console.log('build-client: OK')
console.log('  lib/client.js  ' + Buffer.byteLength(bundle) + ' bytes（ModuleLoader bundle, slot=conversation.input.left）')
